[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "numpy",
    "cy-root",
]

[tool.cibuildwheel]
build = ["cp36-*", "cp37-*", "cp38-*", "cp39-*", "cp310-*", "cp311-*"]
archs = ["auto64"]
skip = ["*-musllinux_*", "*-win32", "*-manylinux_i686"]
